name: SepareWorldItems
version: '${project.version}'
main: com.github.happyuky7.separeworlditems.SepareWorldItems
api-version: 1.16
authors: [ Happyuky7 ]
description: Separe World Items
website: https://github.com/Happyuky7
folia-supported: true
commands:
  separeworlditems:
    aliases: [swi, swis]
    usage: /<command> help
  swimohist:
    aliases: [swimoh]
    usage: /<command> help