#
# SepareWorldItems 1.2.19
# Tutorial: https://github.com/HappyRogelio7/SEPARE-WORLD-ITEMS/wiki
# Discord OR Support: https://discord.gg/3EebYUyeUX
# Config Plugin SepareWorldItems 1.2.19
# Update = true
# Config = 1.2.19-DEV-116
#
general:
  update: true
  update-link: "https://github.com/HappyRogelio7/SEPARE-WORLD-ITEMS/" #Do not change.
  config: 1.2.19-DEV-116 #Do not change
  java-version: 17 #Do not change, This version is build for Java 17.
#
# Options.
#
Options:
  default-groups: "default" #This function is in the testing phase.
  gamemode: false #Save Gamemode player.
  gamemode-default: "SURVIVAL" # SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  flying: false #Save Player Fly Mode. (YES=true, NO=false)
  ender-chest: true #EnderChest YES=true, NO=false.
  #
  # If you are using a custom health system set "health-default-save" to false
  # and set "health-custom-save" to true. If you don't use a custom life system leave it as it is by default.
  #
  health-options:
    health-type: "BUKKIT"
    health-default-save: true #BUKKIT
    health-custom-save: false #CUSTOM
  #
  # Beta Option bypass world:
  #
  bypass-world-options:
    use_bypass: false

#
# Config Plugin SepareWorldItems 1.2.19
#
groups:
  - default
worlds:
  world: default
  world_nether: default
  world_the_end: default