#
# SepareWorldItems
# Version: 1.2.25-DEV-102
# Tutorial: https://github.com/Happyuky7/SEPARE-WORLD-ITEMS/wiki
# Discord OR Support: https://discord.gg/3EebYUyeUX
#

# Config Version: 1.2.25-DEV-102
config-version: 1.2.25-DEV-102

settings:

  debug: false #Debug Mode.

  langs:
    lang: en_US
    auto-download: true #Auto download language files. (Recommended ENABLE)


experimental:
  backups:
    enable: true #Enable or disable automatic backup.
    interval: 1 # Interval in days.
    max-backups: 5 #No recommended to change, maximum number of backups.

# Basic Config for functions.

# Groups:
# Recommended: default, no remove or change.
# You can add more groups.
groups:
  - default
  - otherworldgroup

# Worlds:
# In the worlds section you can set the group for each world.
# Worlds is case sensitive.
# Format --> world: group
worlds:
  world: default
  world_nether: otherworldgroup
  world_the_end: default

# Options:
options:
  default-groups: "default" #This function is in the testing phase.
  gamemode: false #Save Gamemode player.
  gamemode-default: "SURVIVAL" # SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  flying: false #Save Player Fly Mode. (YES=true, NO=false)
  ender-chest: true #EnderChest YES=true, NO=false.
  #
  # If you are using a custom health system set "health-default-save" to false
  # and set "health-custom-save" to true. If you don't use a custom life system leave it as it is by default.
  #
  health-options:
    health-type: "BUKKIT"
    health-default-save: true #BUKKIT
    health-custom-save: false #CUSTOM
  #
  # Beta Option bypass world:
  #
  bypass-world-options:
    use_bypass: false