#
# SepareWorldItems 1.2.22-DEV-100
# Tutorial: https://github.com/HappyRogelio7/SEPARE-WORLD-ITEMS/wiki
# Discord OR Support: https://discord.gg/3EebYUyeUX
# Config Plugin SepareWorldItems 1.2.22-DEV-100
# Update = true
# Config = 1.2.22-DEV-100
#
general:
  update: true
  update-link: "https://github.com/HappyRogelio7/SEPARE-WORLD-ITEMS/" #Do not change.
  config: 1.2.22-DEV-100 #Do not change

experimental:
  lang: en_US #Change the language of the plugin.
  auto-download-lang: true #Automatic download of the language file.
  backups: # Automatic backup of the plugin.
    enable: true #Enable or disable automatic backup.
    time: 1 #Time in minutes.
    max-backups: 5 #Maximum number of backups.
#
# Options.
#
Options:
  default-groups: "default" #This function is in the testing phase.
  gamemode: false #Save Gamemode player.
  gamemode-default: "SURVIVAL" # SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  flying: false #Save Player Fly Mode. (YES=true, NO=false)
  ender-chest: true #EnderChest YES=true, NO=false.
  #
  # If you are using a custom health system set "health-default-save" to false
  # and set "health-custom-save" to true. If you don't use a custom life system leave it as it is by default.
  #
  health-options:
    health-type: "BUKKIT"
    health-default-save: true #BUKKIT
    health-custom-save: false #CUSTOM
  #
  # Beta Option bypass world:
  #
  bypass-world-options:
    use_bypass: false

groups:
  - default
worlds:
  world: default
  world_nether: default
  world_the_end: default