
config-version: 2.0.0-DEV-105-TEST-2

# Settings for the plugin.
settings:

  # Debug mode.
  # This is designed more for developers.
  # Default: false
  debug: false

  langs:

    # Auto download the language file from the GitHub repository. (Recommended enabled)
    # Default: true
    autoDownload: true

    # NOTE: 'langs' is a file that allows you to translate the plugin
    #       to any language that is not in the list of available languages yet.
    lang: "en_US" # Language file. (Default: en_US) | Change REQUIRED restart.

  # Auto configure worlds.
  # Should we add missing worlds to the config?
  # REQUIRED: options.default-group.group to be enabled.
  # Default: false
  auto-configure-worlds: false

  backups:
    # Enable backups.
    # Default: true
    enabled: true

    # Backup interval (default in days).
    # Default: 1
    interval: 1

    # Interval type:
    # Case sensitive.
    # Recommended: d (days), If you have many players for greater security 
    #              You could use hours but it is recommended only every 6 or 12 hours as a minimum.
    #
    # Default: DAYS
    # TYPES:
    # - SECONDS = s
    # - MINUTES = m
    # - HOURS = h
    # - DAYS = d
    interval-type: d

    # Maximum number of backups to keep.
    # Default: 5
    # NOTE: After all 5 are completed, the last of these will be removed so that a new one can be added.
    max-backups: 5

  # Options for the plugin.
  options:

    # Default group.
    # This group is used when the world is not in the list of worlds.
    # ----------------------------------------
    # NOTE: In case you delete the default group in the “groups” list change the group below.
    #       Example: group: otherworldgroup
    # NOTE 2: You can also change the default group if you want to use a group other than “default”.
    # ----------------------------------------
    # Default: enabled and group: default
    default-group:
      enabled: true
      group: default

    # Save options.
    # This option is used to save the player's status when they leave the world
    # ----------------------------------------
    # NOTE: If you disable this option, the player will lose their status when they leave the world.
    # WARNING: If you change any of this when you have time with player inventories make a backup
    #          of your server in case any errors occur.
    # ----------------------------------------
    saves:
      gamemode: true
      # Flying (Include AllowFlight)
      flying: true
      fly-speed: true
      exp: true
      enderchest: true
      inventory: true
      potion-effects: true
      food-level: true
      off-hand: true
      health: true


  health-options:
    # TYPES:
    # - BUKKIT
    # - CUSTOM (BYPASS) | (Use it if the plugin you're using isn't supported here, if you want support added, contact us via Discord and create a ticket.)
    # - AURA_SKILLS (Requires AuraSkills (AureliumSkills) plugin and integration enabled)
    type: BUKKIT

# Integrations:
integrations:
  placeholderapi:
    # Enable PlaceholderAPI support.
    # Default: true
    # Required: PlaceholderAPI plugin.
    enabled: true
  auraskills:
    # Enable AuraSkills (AureliumSkills) support.
    # Default: false
    # Required: AuraSkills (AureliumSkills) plugin.
    # NOTE: BETA!
    enabled: false
  worldguard:
    # Enable WorldGuard support.
    # Default: false
    # Required: WorldGuard plugin.
    enabled: false
  essentials:
    # Enable Essentials support.
    # Default: false
    # Required: Essentials plugin.
    enabled: false
  

# Groups:
# Recommended: default, no remove or change.
# You can add more groups.
groups:
  - default
  - otherworldgroup

# Worlds:
# In the worlds section you can set the group for each world.
# Worlds is case sensitive.
# Format --> world: group
worlds:
  world: default
  world_nether: otherworldgroup
  world_the_end: default


# WorldGuard Regions: (BETA!)
# 
# WARNING: This section is only available if the WorldGuard integration is enabled.
# WARNING 2: NEW IMPLEMENTATION, THIS IS NO FULLY TESTED.
# WARNING 3: MAKE A BACKUP OF YOUR SERVER IN CASE ANY ERRORS OCCUR
worldguard-regions:
  # In the worldguard-regions section you can set the group for each WorldGuard region.
  #
  # NOTE: This is only available if the WorldGuard integration is enabled.
  # NOTE 2: Regions is case sensitive.
  # NOTE 3: If a player is in multiple regions, the region with the highest priority will be used.
  # NOTE 4: If a player is not in any region, the world group will be used.
  # NOTE 5: If a region is not in the list, the world group will
  #

  # Groups for regions.
  groups:
  - defaultregiongroup
  - otherregiongroup

  # Regions and their groups.
  # Format --> region: group
  # Regions is case sensitive.
  # INFO: If the same region is in another world it will also affect.
  regions:
    spawn: defaultregiongroup
    pvp: otherregiongroup


# EssentialsX (BETA!)
essentialsx:
  vanish-bypass: true # Allow players in vanish to bypass the plugin restrictions.


auraskills:
  save-mana: true # Save Mana to change world
  # Others Skills and in comming soon update.
  # save-skillnamehere: boolean


# Metrics:
# Should we enable metrics?
# Default: true
# NOTE: This no implemented in this version. It will be available in future versions.
metrics:
  enabled: true



