name: SepareWorldItems
version: ${project.version}
main: com.github.happyuky7.separeWorldItems.SepareWorldItems
api-version: '1.16'
authors: [ Happyuky7 ]
description: SepareWorldItems
website: https://github.com/Happyuky7
folia-supported: true
soft-depend: [ PlaceholderAPI, EssentialsX, WorldGuard, Multiverse-Core, AuraSkills ]
commands:
  separeworlditems:
    description: SepareWorldItems command
    usage: /<command>